version: 2
jobs:
  test:
    working_directory: ~/circleci-demo-python-django
    docker:
      - image: circleci/python:3.7.3
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:11.2
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7.3/site-packages
      - run: cp "./.circleci/secret_settings.py" "./ds4reboot/secret_settings.py"
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Pipfile" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            pip install --upgrade pip
            pipenv install
      - save_cache:
          paths:
            - ./
          key: v1-dependencies-{{ checksum "Pipfile" }}
      - run:
          command: |
            python manage.py test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
  deploy:
    docker:
      - image: circleci/python:3.7.3
    working_directory: ~/docker/
    steps:
      - add_ssh_keys:
          fingerprints:
            - "cc:61:91:7a:32:93:c1:8e:00:ac:1b:96:07:7c:3a:c7"
      - run:
          name: Checkout master
          command: |
            ssh $SSH_USER@$SSH_HOST -o "StrictHostKeyChecking no" 'cd /root/docker/ds4reboot/ ;and git checkout develop ;and git pull'
      - run:
          name: Restart gunicorn
          command: |
            ssh $SSH_USER@$SSH_HOST 'cd /root/docker/ ;and docker build .f ds4reboot.Dockerfile -t django-custom ;and docker-compose up -d'
workflows:
  version: 2
  deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: develop