version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-python-django
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run: cp "./.circleci/secret_settings.py" "./ds4reboot/secret_settings.py"
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            pip install --upgrade pip
            pip install --user -r requirements.txt
      - save_cache:
          paths:
            - ./
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python manage.py test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
  deploy-job:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "73:83:79:c1:38:09:24:b7:f9:28:65:cd:66:34:40:bf"
      - executor:
        working_directory: "~/srv/ds4reboot/"
      - run:
          name: Install Python dependencies in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements
      - checkout
      - run:
          name: Restart gunicorn
          command: |
            sudo service gunicorn restart
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master